### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by ifischerova** [MijaHinn/portfolio#1]
Ahoj Míšo, 

díky za odevzdání, WOW, skvělá práce 👏 

Moc se mi to líbí naprosto po všech stránkách a velká pecka, že jsi se nebála snad ničeho, co jsme v kurzu dělali 👍 
I Lighthouse audit vychází takřka dokonale.

Z hlediska požadavků na závěrečný projekt máš samozřejmě splněno, takže klobouček a gratulace veliká 🥇 

Kde jsi hledala inspiraci? Já se patlám se svýma stránkama asi rok a půl a furt to akorát předělávám a nejsem spokojená. Tohle se mi líbí moc. 

Pokud jde o nějaké tipy:
- bude určitě potřeba doladit formulář, pokud doplním jméno, tak má tendenci mě někam přesměrovat, nicméně to hodí chybovou hlášku. Ale to samozřejmě nespadá do ranku Kodérky.
- na mobilu bych asi dala pryč slovo "Kontakt" z footeru (a nechala tam prostě jen emailovou adresu), ale to je čistě můj osobní názor :)

**Comment by MijaHinn** [comment]
Ahoj Ivko,
děkuji, moc si toho vážím a jsem ráda, že se web líbí. :)

Inspiraci jsem hledala různě po internetu. Koukala jsem, jakým způsobem mají udělaná portfolia ostatní. A potom jsem si udělala grafický návrh ve Figmě, aby se mi to lépe kódovalo.

Jinak o formuláři vím, že nefunguje. Určitě na tom webu budu ještě dále pracovat, takže i formulář mám pak v plánu zprovoznit. :) Kontakt na mobilu zvážím. Děkuji za tipy :)
